steps:
  # Construir la imagen Docker (asumiendo que usas Dockerfile o Dockerfile.deploy)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/informationsystem2/auto-repair-shop-fastapi:$COMMIT_SHA'
      - '-f'
      - 'Dockerfile.deploy'          # o 'Dockerfile.deploy' si lo tienes con otro nombre
      - '.'

  # Subir la imagen a Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/github.com/informationsystem2/auto-repair-shop-fastapi:$COMMIT_SHA'

  # Desplegar en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auto-repair-shop-fastapi'      # Nombre de tu servicio en Cloud Run
      - '--image'
      - 'gcr.io/$PROJECT_ID/github.com/informationsystem2/auto-repair-shop-fastapi:$COMMIT_SHA'
      - '--region'
      - 'southamerica-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'       # Si debe ser público
      - '--quiet'

images:
  - 'gcr.io/$PROJECT_ID/github.com/informationsystem2/auto-repair-shop-fastapi:$COMMIT_SHA'
